### ISSUE TITLE
Error: Invalid key format for securityKeys.S2_AccessControl option

### ISSUE THREAD

**Issue by Stubbs** [kpine/zwave-js-server-docker#23]
```
zwavejs                     | Starting zwave-server: zwave-server --config options.js /dev/zwave
zwavejs                     | Error: failed loading config file /app/options.js
zwavejs                     | Error: Invalid key format for securityKeys.S2_AccessControl option
zwavejs                     |     at normalizeKey (/app/node_modules/@zwave-js/server/dist/bin/server.js:18:11)
zwavejs                     |     at /app/node_modules/@zwave-js/server/dist/bin/server.js:66:53
zwavejs                     |     at Object.<anonymous> (/app/node_modules/@zwave-js/server/dist/bin/server.js:145:3)
zwavejs                     |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
zwavejs                     |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
zwavejs                     |     at Module.load (node:internal/modules/cjs/loader:981:32)
zwavejs                     |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
zwavejs                     |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
zwavejs                     |     at node:internal/main/run_main_module:17:47
```

I've just updated to the latest docker image and when I try and start it I get the error above ...

**Comment by kpine** [comment]
I'm not seeing any problem myself. Double check your S2 Access Control key format.
